# Generated by Django 5.0.3 on 2024-04-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INSTITUTE_ADMITTED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NON_INSTITUTE_ADMITTED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('vehicle_no', models.CharField(max_length=10)),
            ],
        ),
    ]
