# Generated by Django 5.0.3 on 2024-04-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_institute_admitted',
            name='created_at',
            field=models.CharField(max_length=20),
        ),
    ]
