# Generated by Django 5.0.3 on 2024-04-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0002_alter_non_institute_admitted_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='non_institute_admitted',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
    ]
