# Generated by Django 5.0.3 on 2024-04-09 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0004_alter_non_institute_admitted_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INSTITUTE_ADMITTED',
        ),
    ]
