# Generated by Django 5.0.3 on 2024-04-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0006_institute_admitted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='INSTITUTE_ADMITTED',
        ),
    ]
