# Generated by Django 5.0.3 on 2024-04-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEBSITE', '0012_alter_institute_admitted_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STUDENTS_DATA',
        ),
    ]
